### ISSUE TITLE
Kompatibilität

### ISSUE THREAD

**Issue by miterion** [d120/still-alive#1]
Von der Mailingliste:

Das Skript läuft derzeit nur bis Firefox 52. Alle
aktuellen Browser spielen Lied und Liedtext nicht ab, Namensliste geht
überall. Daten liegen z. B. unter Ophase/Ophase-W19/still-alive. Kann
sich das für die Zukunft mal jemand angucken?

**Comment by luelista** [comment]
ich schaus mir grad an, liegt wohl dran dass die browser kein autoplay auf `<audio>`-tags mehr erlauben
